version: '3.8'

services:
  app:
    env_file: .env
    environment:
      - POSTGRES_DB_HOST=postgres
    build:
      context: .
      dockerfile: build/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${GRPC_PORT}:${GRPC_PORT}"

  postgres:
    env_file: .env
    image: postgres:13
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 3s
      retries: 3