// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.2
// source: api/device-tracker.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ToUpperRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InputString string `protobuf:"bytes,1,opt,name=input_string,json=inputString,proto3" json:"input_string,omitempty"`
}

func (x *ToUpperRequest) Reset() {
	*x = ToUpperRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_device_tracker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToUpperRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToUpperRequest) ProtoMessage() {}

func (x *ToUpperRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_tracker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToUpperRequest.ProtoReflect.Descriptor instead.
func (*ToUpperRequest) Descriptor() ([]byte, []int) {
	return file_api_device_tracker_proto_rawDescGZIP(), []int{0}
}

func (x *ToUpperRequest) GetInputString() string {
	if x != nil {
		return x.InputString
	}
	return ""
}

type ToUpperResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConvertedString string `protobuf:"bytes,1,opt,name=converted_string,json=convertedString,proto3" json:"converted_string,omitempty"`
}

func (x *ToUpperResponse) Reset() {
	*x = ToUpperResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_device_tracker_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToUpperResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToUpperResponse) ProtoMessage() {}

func (x *ToUpperResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_tracker_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToUpperResponse.ProtoReflect.Descriptor instead.
func (*ToUpperResponse) Descriptor() ([]byte, []int) {
	return file_api_device_tracker_proto_rawDescGZIP(), []int{1}
}

func (x *ToUpperResponse) GetConvertedString() string {
	if x != nil {
		return x.ConvertedString
	}
	return ""
}

var File_api_device_tracker_proto protoreflect.FileDescriptor

var file_api_device_tracker_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2d, 0x74, 0x72, 0x61,
	0x63, 0x6b, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x5f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x22, 0x33, 0x0a, 0x0e, 0x54, 0x6f,
	0x55, 0x70, 0x70, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c,
	0x69, 0x6e, 0x70, 0x75, 0x74, 0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x22,
	0x3c, 0x0a, 0x0f, 0x54, 0x6f, 0x55, 0x70, 0x70, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x65, 0x64, 0x5f,
	0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x6f,
	0x6e, 0x76, 0x65, 0x72, 0x74, 0x65, 0x64, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x32, 0x64, 0x0a,
	0x14, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4c, 0x0a, 0x07, 0x54, 0x6f, 0x55, 0x70, 0x70, 0x65, 0x72,
	0x12, 0x1e, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65,
	0x72, 0x2e, 0x54, 0x6f, 0x55, 0x70, 0x70, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1f, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65,
	0x72, 0x2e, 0x54, 0x6f, 0x55, 0x70, 0x70, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x48, 0x5a, 0x46, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x64, 0x61, 0x6b, 0x31, 0x35, 0x31, 0x34, 0x34, 0x39, 0x2f, 0x49, 0x4f, 0x54, 0x5f,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x5f, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x5f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x3b, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_device_tracker_proto_rawDescOnce sync.Once
	file_api_device_tracker_proto_rawDescData = file_api_device_tracker_proto_rawDesc
)

func file_api_device_tracker_proto_rawDescGZIP() []byte {
	file_api_device_tracker_proto_rawDescOnce.Do(func() {
		file_api_device_tracker_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_device_tracker_proto_rawDescData)
	})
	return file_api_device_tracker_proto_rawDescData
}

var file_api_device_tracker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_device_tracker_proto_goTypes = []interface{}{
	(*ToUpperRequest)(nil),  // 0: device_tracker.ToUpperRequest
	(*ToUpperResponse)(nil), // 1: device_tracker.ToUpperResponse
}
var file_api_device_tracker_proto_depIdxs = []int32{
	0, // 0: device_tracker.DeviceTrackerService.ToUpper:input_type -> device_tracker.ToUpperRequest
	1, // 1: device_tracker.DeviceTrackerService.ToUpper:output_type -> device_tracker.ToUpperResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_device_tracker_proto_init() }
func file_api_device_tracker_proto_init() {
	if File_api_device_tracker_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_device_tracker_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ToUpperRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_device_tracker_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ToUpperResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_device_tracker_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_device_tracker_proto_goTypes,
		DependencyIndexes: file_api_device_tracker_proto_depIdxs,
		MessageInfos:      file_api_device_tracker_proto_msgTypes,
	}.Build()
	File_api_device_tracker_proto = out.File
	file_api_device_tracker_proto_rawDesc = nil
	file_api_device_tracker_proto_goTypes = nil
	file_api_device_tracker_proto_depIdxs = nil
}
